### PR TITLE
Rework notebook

### PR DESCRIPTION
**Pull request by iamashwin99**
Updated a few dc strings (with input from Heiko)
pulled back the plot of energy convergence.

### CODE REVIEW

**Comment by fangohr** [comment]
Looks good; thank you.

Did you work out the comments and the `FromScratch=Yes` addition with one of the Octopus developers?

**Review by fangohr — APPROVED** [review]
Looks good, thank you.

**Comment by iamashwin99** [comment]
> FromScratch=Yes

`FromScratch=Yes` flag tells the octopus not to use the checkpoint files to restart the calculation but rather start from scratch.
This is useful when we want to plot the energy convergence as a function of iterations. If the flag was not used, then the energies might have already converged in the checkpoint files, and so the number of iterations run is few.

**Comment by KevinYanesG** [comment]
I can't pull other branches apart from main, so I needed to view the notebook via GitHub:
can you see the image in the notebook?
image

(The other files must be placed here one by one --> one bracket is missing
One would look at the last 20 lies to check if the job ran successfully or if there was any warning. A typical successful output looks like: --> lines instead of lies
If no system is specfically set, postopus will create a `default` system called `default`. --> I think the first default shouldn't be surrounded with code brackets
image
--> run insted of r? maybe it is just a github problem

calculation mode go for geometry optimization. --> postopus doesn't support the `go` calculation mode. I didn't know it existed. Maybe it is worth to open an issue in the postopus repo for this?

In the previous sections we saw how to access any scalar or vector field generated by our calculation. Let's explore the typical workflow of analyzing the data (slicing and plotting). First let's load the density data: --> commas after sections and First are missing

First let us import the holoviews library as well as the plotting backends we will use: --> same here

Are the methane plots less "boring" than last time? I can't execute them

Could you please check the text with grammarly? I think it would be a good idea to avoid typos

Otherwise, it looks good, thanks

**Comment by iamashwin99** [comment]
* I can see the images when I use the jupyter lab from Notebook. The change to the path was a commit you made I believe.
* The bracket is there in the notebook, maybe you missed it on the web version of the notebook.
* There are no changes in the methane example ( do you have any idea to brighten it up?)
*  Remaining typos are corrected

**Pull request merged**
